fix nix flake on non-x86_64-linux platforms (#84)
* fix nix flake on non-x86_64-linux platforms

due to an accidental use of the build pkgs when defining
overlays.

Fixes:
```
error: a 'x86_64-linux' with features {} is required to build
'/nix/store/7p6q6dypdcfx28dhzl6p52hxv5x51sl3-c2eec4dd1de7d0da2d2f76e5e7f2b567901f4e2c.patch.drv',
but I am a 'aarch64-darwin' with features {apple-virt, benchmark, big-parallel, nixos-test}
```

* it's hard to give a useful error message because of nix's laziness

the error from misuse of input will only be raised when it is evaluated
in some output.

* checkBadAttrs

* nixfmt

* remove ocaml patch and just disable tests