nix: fix after gtirb loader (#176)
Closes https://github.com/agle/bincaml/issues/175

We get "Error: Unbound value Bool.to_string" in Nix but not outside of Nix and this seems to be fixed by using `Stdlib.Bool` so that's what we're gonna use.

I also disable tests because the `  src = nix-gitignore.gitignoreSource [ "nix" "flake.nix" "flake.lock" ] ./..;` seems to exclude the submodule for whatever reason. Tests are still enabled in the dev shell for nixos users.